<FirstScreen>:
    GridLayout:
        cols: 1
        padding: 10
        spacing: 10
        Image:
            source: 'files/sunny.jpg'
            size_hint_y: 0.8
        TextInput:
            size_hint_y: 0.08
        Button:
            text: 'Search Image'
            size_hint_y: 0.12
            on_press: root.search_image()


<RootWidget>:
    FirstScreen:
        id: first_screen
        name: 'first_screen'
